### ISSUE TITLE
Still developed?

### ISSUE THREAD

**Issue by martinjo** [Smart-Display/SmartDisplay-Server#53]
Is this still being developed?

What features are planned?

**Comment by MCeddy** [comment]
Hey. Yes the project is still in development. But currently I only maintaing updates.

In the future I plane to refactore the server and controller so it should easier to add external apps (linke a app store).

Also try to use direkt communication between controller ans server (so that the view data not using MQTT anymore).

But starting after the summer.

Do you have any nice ideas for the project?

Best regards

René

**Comment by MCeddy** [comment]
publish roadmap soon

**Comment by MCeddy** [comment]
publish roadmap soon
